apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: grafana-cert
  namespace: yatai-monitoring
spec:
  acme:
    # Email address used for ACME registration
    email: ${ACME_MAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: grafana-tls
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
