apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-grafana
  namespace: yatai-monitoring
spec:
  acme:
    email: ${ACME_MAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-grafana-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
