import pandas as pd
import requests
from zenml.steps import step
import json
#TODO add discord webhook
DISCORD_URL = (
    'https://discord.com/api/webhooks/1128669713304662076/BE0-0j4d_q3-nkd5U-DFeouHzfmE9fxXgePJd_L8IDCK3Dxsw3BJlVPNPTWWjYBkfGub'
)


@step(enable_cache=False)
def discord_alert(
    update: str,
) -> bool:
    """Send a message to the discord channel to report model status.

    Args:
        datadrift: The drift report generated by evidently
    """
    update = json.loads(update)["update"][0]
    url = DISCORD_URL
    data = {
        "content": "Model updated" if update else "No performance increase achived",
        "username": "Trainings Bot",
    }
    result = requests.post(url, json=data)

    try:
        result.raise_for_status()
    except requests.exceptions.HTTPError as err:
        print(err)
    else:
        print(
            "Posted to discord successfully, code {}.".format(
                result.status_code
            )
        )
    print("Model updated" if update else "No performance increase achived")
    return update
